"""updated relationship between user and blog tables

Revision ID: bba3f14d7297
Revises: 851875096b14
Create Date: 2024-07-06 21:08:15.521816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba3f14d7297'
down_revision = '851875096b14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
